Add missing library to link
/var/uhubuild/work/compile/src/main.cpp:19:10: fatal error: QApplication: Nincs ilyen fájl vagy könyvtár
 #include <QApplication>
          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/qterminal.dir/build.make:179: CMakeFiles/qterminal.dir/src/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/uhubuild/work/compile/src/mainwindow.cpp:19:10: fatal error: QDockWidget: Nincs ilyen fájl vagy könyvtár
 #include <QDockWidget>
          ^~~~~~~~~~~~~
compilation terminated.